version: '3'

services:
  webapp:
    container_name: webapp
    hostname: webapp
    image: node:10.16.3-alpine
    ports:
      - 3333:3333
    volumes:
      - ./:/usr/bin/webapp
    working_dir: /usr/bin/webapp
    command: npm run qa