version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: database
      MONGO_INITDB_ROOT_DATABASE: database
      MONGO_INITDB_ROOT_PASSWORD: tm8Iw6XegXXYrVja
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
